#- name: Load Maven
#  ansible.builtin.include_role:
#    name: common
#    tasks_from: maven
#
#- name: Install mysql client
#  ansible.builtin.dnf:
#    name: mysql
#    state: installed
#
#- name: Load sql file
#  ansible.builtin.shell: mysql -h mysql-{{ env }}.kndevops72.online -uroot -p{{ lookup('hashi_vault', 'roboshop-{{env}}/data/shipping:mysql_root_password token={{vault_token}} url=http://vault-internal.kndevops72.online:8200')}} < /app/db/{{ item }}.sql
#  loop:
#    - schema
#    - app-user
#    - master-data
#
#- name: Restart shipping
#  ansible.builtin.systemd_service:
#    name: shipping
#    state: restarted

- name: Install Docker
  ansible.builtin.include_role:
    name: common
    tasks_from: docker