#- name: Load NodeJS Service
#  ansible.builtin.include_role:
#    name: common
#    tasks_from: nodejs.yml
#
#- name:  Copy MongoDB repo file
#  ansible.builtin.copy:
#    src: mongodb.repo
#    dest: /etc/yum.repos.d/mongodb.repo
#
#- name:  Install MongoDB
#  ansible.builtin.dnf:
#    name: mongodb-mongosh
#    state: installed
#
#- name: Load Master data
#  ansible.builtin.shell: mongosh --host mongodb-{{ env }}.kndevops72.online </app/db/master-data.js
#
#- name: Restart Catalogue Service
#  ansible.builtin.systemd_service:
#    name: catalogue
#    state: restarted

- name: Install Docker
  ansible.builtin.include_role:
    name: common
    tasks_from: docker

- name: Start App container
  containers.podman.podman_container:
    name: catalogue
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/catalogue
    state: started
    restart: true
    restart_policy: "always"
    ports:
      - "8080:8080"
    env:
      MONGO: "{{ lookup('hashi_vault', 'roboshop-{{env}}/data/catalogue:MONGO token={{vault_token}} url=http://vault-internal.kndevops72.online:8200')}}"
      MONGO_URL: "{{ lookup('hashi_vault', 'roboshop-{{env}}/data/catalogue:MONGO_URL token={{vault_token}} url=http://vault-internal.kndevops72.online:8200')}}"