- name: Set Prompt
  ansible.builtin.shell: set-prompt {{ component }}-{{ env }}

- name: Increase disk partition
  ansible.builtin.shell: growpart /dev/nvme0n1 4
  ignore_errors: yes

- name: Extend lv
  ansible.builtin.shell: lvextend -r -L {{item.size}} /dev/mapper/RootVG-{{ item.volume }}
  loop: "{{ lvm_sizes }}"